[package]
name = "sea_orm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.24"
sea-orm = { version = "0.9.2", features = ["sqlx-mysql", "runtime-async-std-native-tls", "macros"] }
